#!/bin/bash
clear
echo "DBG --Project2--"
echo "compiling..."
rm ./main.o
g++ -c -Wall -g ./Project2/main.cpp ./Project2/NN.cpp -std=c++17
# -Wfatal-errors -fpermissive -Wall -Werror
# -fsyntax-only
echo "linking..."
g++ -o ./x64/Debug/g++_Project2 main.o NN.o -pthread -lX11 -lsfml-system -lsfml-window -lsfml-graphics
#echo "starting..."
#./run/media/dream11x/dreamIIx/programming/C++/Project2/x64/Debug/g++_Project2
