#!/bin/bash
clear
echo "DBG _TEST_"
echo "compiling..."
g++ -fpermissive -c _TEST_/cnn.cpp
# _TEST_/NN.cpp 
# -Wfatal-errors -fpermissive -Wall -Werror
# -fsyntax-only
echo "linking..."
g++ -o ./x64/Release/Test cnn.o NN.o -Wall -g -I/run/media/dream11x/dreamIIx/programming/C++/_TEST_/_TEST_/opencv2 -L/usr/lib -pthread -lX11 -std=c++17 -lopencv_stitching -lopencv_superres -lopencv_videostab -lopencv_aruco -lopencv_bgsegm -lopencv_bioinspired -lopencv_ccalib -lopencv_dnn -lopencv_dpm -lopencv_fuzzy -lopencv_line_descriptor -lopencv_optflow -lopencv_plot -lopencv_reg -lopencv_saliency -lopencv_stereo -lopencv_structured_light -lopencv_rgbd -lopencv_surface_matching -lopencv_tracking -lopencv_datasets -lopencv_text -lopencv_face -lopencv_xfeatures2d -lopencv_shape -lopencv_video -lopencv_ximgproc -lopencv_calib3d -lopencv_features2d -lopencv_flann -lopencv_xobjdetect -lopencv_objdetect -lopencv_ml -lopencv_xphoto -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_photo -lopencv_imgproc -lopencv_core
cd /run/media/dream11x/dreamIIx/programming/C++/_TEST_
# -O2
#echo "starting..."
#./g++_Project2